#        _________                                  __ __________        __   
#       /   _____/__ ________ ______   ____________/  |\______   \ _____/  |_ 
#       \_____  \|  |  \____ \\____ \ /  _ \_  __ \   __\    |  _//  _ \   __\
#       /        \  |  /  |_> >  |_> >  <_> )  | \/|  | |    |   (  <_> )  |  
#      /_______  /____/|   __/|   __/ \____/|__|   |__| |______  /\____/|__|  
#              \/      |__|   |__|                             \/             
#
#                      SupportBot version 6.0
#                      Created by Emerald Services
#                      Installed with MIT License

# General Bot Configuration

Token: "TOKEN"
Prefix: "!!"
Bot_Name: "SupportBot DEV"

BotActivity: "SB-6.0 dev-0.1"
ActivityType: "PLAYING"

# Embed Configuration

EmbedColour: "#04b545"
EmbedFooter: "SupportBot | The #1 Supportive Discord Bot"

ErrorColour: "#d12519"
SuccessColour: "#04b545"
WarningColour: "#fca117" 

# Role Configuration

AutoRole: "Member"

Staff: "Support"
Admin: "Admin"

# Ticket Configuration

TicketChannel: "ticket"
TicketCategory: "Tickets"
maxTickets: 5

Ticket_Title: "Server Support"
TicketMessage: "Hello **<@%ticketauthor%>**, Thank you for creating a support ticket\nPlease wait patiently whilst a member of our team reaches out to you."
NoTicketSubject: "No Reason Provided!"

ReactToCreateTicket: true
ReactionForTicket: 🎫

# Ticket Department Configuration

Department_1: "Support"
Department_2: "Report"
Department_3: "Other"

DepartmentRole_1: "Support"
DepartmentRole_2: "Admin"
DepartmentRole_3: "Support"

# System Message Configuration

SystemMessages: "true"

SystemMessage_Channel: "system-messages"
SystemMessages_Embed: "true"

WelcomeMessage: "Hello %membertag%, Welcome to %guildname%!"
LeaveMessage: "Goodbye %membertag%, Thank you for visting %guildname%!"

# LINKS Configuration

LinksTitle: "Quick Links"

LINKS:
  "Website": "https://www.example.com"
  "Store": "https://store.example.com"
  "Discord": "https://discord.gg/example"

# Suggestions Configuration

SuggestionChannel: "suggestions"
SuggestionTitle: "Suggestion"
SuggestionStarter: "What would you like to suggest?"
SuggestReact_1: 👍
SuggestReact_2: 👎

# Poll Configuration

PollChannel: "polls"
PollTitle: "Suggestion"
PollStarter: "What would you like to create a poll about?"
PollReact_1: 👍
PollReact_2: 👎


# Announcement Configuration

AnnouncementChannel: "announcements"
AnnouncementTitle: "Servername Announcement"
AnnouncementIcon: "https://i.imgur.com/HbkZyB7.png"

AnnouncementStarter: "What would you like to announce?"

MentionedRole: "@everyone"

# General Command Configuration

HelpCommand: "help"
LinksCommand: "links"
PingCommand: "ping"
SuggestCommand: "suggest"

# Staff Command Configuration

SayCommand: "say"
ChatLockCommand: "lock"
ChatUnlockCommand: "unlock"

# Management Command Configuration

AnnounceCommand: "announce"

# Support Command Configuration

NewTicket: "ticket"
CloseTicket: "close"
AddUser: "add"
RemoveUser: "remove"
RenameTicket: "rename"







